# Generated by Django 2.2.4 on 2020-07-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0002_auto_20200720_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
